## Parameters to test ABC simulation pipeline (msprime, snakefile, run_gencomp1.sh)

 window_size: "50000"
 window_step_size: "10000"
 informative_site_method: "derived_in_archaic"
 informative_site_range: "0"

 null_dataset:
     name: "null"
     directory: "/Genomics/akeylab/abwolf/SimulatedDemographic/ABC/Sriram/null"
     # VCF Info
     vcf_file_pattern: "vcfs/{sample}.mod.vcf.gz"
     chrom_sizes: "1000000"
     # Population info
     population_file: "base.popfile"
     archaic_populations:
         - "Neand1"
     modern_populations:
         - "EUR"
         - "ASN"

 test_dataset:
     name: "n1_0.0_mAfB_0.0_mBAf_0.0_mAfEu_0.0_mEuAf_0.0"
     directory: "/Genomics/akeylab/abwolf/SimulatedDemographic/ABC/Sriram/null"
     # VCF Info
     vcf_file_pattern: "vcfs/{sample}.mod.vcf.gz"
     chrom_sizes: "1000000"
     # Population info
     population_file: "base.popfile"
     archaic_populations:
         - "Neand1"
     modern_populations:
         - "EUR"
         - "ASN"
