
 window_size: "50000"
 window_step_size: "10000"
 informative_site_method: "derived_in_archaic"
 informative_site_range: "0"

 null_dataset:
     name: "null"
     directory: "/Genomics/akeylab/abwolf/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Tenn/n1_0.1/null"
     # VCF Info
     vcf_file_pattern: "vcfs/{sample}.mod.vcf.gz"
     chrom_sizes: "1000000"
     # Population info
     population_file: "Tenn.popfile"
     archaic_populations:
         - "Neand1"
     modern_populations:
         - "EUR"
         - "ASN"

 test_dataset:
     name: "Tenn_n1_0.1_mAfB_0.0_mBAf_0.00001_mAfEu_0.0_mEuAf_0.0"
     directory: "/Genomics/akeylab/abwolf/SimulatedDemographic/Sstar/chr1_variable_ref/simulations/Tenn/n1_0.1/n1_0.1_mAfB_0.0_mBAf_0.00001_mAfEu_0.0_mEuAf_0.0"
     # VCF Info
     vcf_file_pattern: "vcfs/{sample}.mod.vcf.gz"
     chrom_sizes: "1000000"
     # Population info
     population_file: "Tenn.popfile"
     archaic_populations:
         - "Neand1"
     modern_populations:
         - "EUR"
         - "ASN"

